--------------------------------------------------------
--  File created - Quarta-feira-Agosto-28-2013   
--------------------------------------------------------
DROP TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_CURSOS" cascade constraints;
DROP TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_AREA" cascade constraints;
DROP TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_ESTADO_CURSO" cascade constraints;
DROP TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_MODULOS" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence GP_CURSOSEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GEST_CLIENTES"."GP_CURSOSEQ"  MINVALUE 0 MAXVALUE 99999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table GP_FORMACAO_TEST_CURSOS
--------------------------------------------------------

  CREATE TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_CURSOS" 
   (	"ID_CURSO" NUMBER, 
	"CURSO" VARCHAR2(20 BYTE), 
	"VERSAO" VARCHAR2(20 BYTE), 
	"DESCRICAO" VARCHAR2(20 BYTE), 
	"DURACAO" NUMBER, 
	"INSTANCIAVEL" VARCHAR2(20 BYTE), 
	"ORIGINAL" VARCHAR2(20 BYTE), 
	"CATALOGO" VARCHAR2(20 BYTE), 
	"CDFORNECEDOR" VARCHAR2(20 BYTE), 
	"VERSAOFORNECEDOR" VARCHAR2(20 BYTE), 
	"ID_AREA" NUMBER, 
	"ID_ESTADOCURSO" NUMBER, 
	"ID_MODULO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GP_FORMACAO_TEST_AREA
--------------------------------------------------------

  CREATE TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_AREA" 
   (	"ID_AREA" NUMBER, 
	"AREA" VARCHAR2(20 BYTE), 
	"ID_RTP" NUMBER, 
	"RTP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GP_FORMACAO_TEST_ESTADO_CURSO
--------------------------------------------------------

  CREATE TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_ESTADO_CURSO" 
   (	"ID_CURSO_STATUS" NUMBER, 
	"ESTADO_CURSO" VARCHAR2(20 BYTE), 
	"DATA_ESTADO" DATE, 
	"RESPONSAVEL" VARCHAR2(20 BYTE), 
	"NOTAS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GP_FORMACAO_TEST_MODULOS
--------------------------------------------------------

  CREATE TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_MODULOS" 
   (	"ID_MODULO" NUMBER, 
	"SEQ_MODULO" NUMBER, 
	"MODULO" VARCHAR2(20 BYTE), 
	"DESCRICAO" VARCHAR2(20 BYTE), 
	"ID_SESSAO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS
SET DEFINE OFF;
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('11','Curso cv11','cv11','Criado na APP','11','false','true','false',null,null,null,null,null);
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('8','Curso8','cv08','Criado na APP','15','false','true','false','Forn1','cv-forn1',null,null,null);
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('12','Advanced Adf','1.0',null,'5','false','false','false','oracle','123456gc10',null,null,null);
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('9','Curso9','cv09','Criado na APP','9','false','true','false','Forn1','cv-forn1',null,null,null);
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('6','Curso6','cv06','Criado na APP','6','false','true','false','Forn1','cv-forn1',null,null,null);
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('10','Curso10','cv10','Criado na APP','10','false','true','false','Forn1','cv-forn1',null,null,null);
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('0','Curso1','cv01','Criado na DB','2','TRUE','TRUE','TRUE','F02','CVF0','0','0','0');
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('1','Curso2','cv02','Criado na DB','1','TRUE','TRUE','FALSE','Fornecedor02','CVF02','0','0','0');
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('2','Curso3','cv00','Criado na DB','4','FALSE','TRUE','FALSE','CF001','CVF0001','1','0','1');
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('7','Curso7','cv07','Criado na APP','7','false','true','false','Forn1','cv-forn1',null,null,null);
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('4','Curso4','cv04','Criado na APP','4','false','true','false','Forn1','cv-forn1',null,null,null);
Insert into GEST_CLIENTES.GP_FORMACAO_TEST_CURSOS (ID_CURSO,CURSO,VERSAO,DESCRICAO,DURACAO,INSTANCIAVEL,ORIGINAL,CATALOGO,CDFORNECEDOR,VERSAOFORNECEDOR,ID_AREA,ID_ESTADOCURSO,ID_MODULO) values ('5','Curso5','cv05','Criado na APP','5','false','true','false','Forn1','cv-forn1',null,null,null);
--------------------------------------------------------
--  DDL for Index TEST_CURSOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GEST_CLIENTES"."TEST_CURSOS_PK" ON "GEST_CLIENTES"."GP_FORMACAO_TEST_CURSOS" ("ID_CURSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GP_FORMACAO_TEST_CURSOS
--------------------------------------------------------

  ALTER TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_CURSOS" MODIFY ("ID_CURSO" NOT NULL ENABLE);
 
  ALTER TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_CURSOS" ADD CONSTRAINT "TEST_CURSOS_PK" PRIMARY KEY ("ID_CURSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GP_FORMACAO_TEST_CURSOS
--------------------------------------------------------

  ALTER TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_CURSOS" ADD CONSTRAINT "GP_FORMACAO_TEST_CURSOS_G_FK1" FOREIGN KEY ("ID_MODULO")
	  REFERENCES "GEST_CLIENTES"."GP_FORMACAO_TEST_MODULOS" ("ID_MODULO") ENABLE;
 
  ALTER TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_CURSOS" ADD CONSTRAINT "GP_FORMACAO_TEST_CURSOS_G_FK2" FOREIGN KEY ("ID_ESTADOCURSO")
	  REFERENCES "GEST_CLIENTES"."GP_FORMACAO_TEST_ESTADO_CURSO" ("ID_CURSO_STATUS") ENABLE;
 
  ALTER TABLE "GEST_CLIENTES"."GP_FORMACAO_TEST_CURSOS" ADD CONSTRAINT "GP_FORMACAO_TEST_CURSOS_G_FK3" FOREIGN KEY ("ID_AREA")
	  REFERENCES "GEST_CLIENTES"."GP_FORMACAO_TEST_AREA" ("ID_AREA") ENABLE;
--------------------------------------------------------
--  DDL for Trigger GP_CURSOS_PK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GEST_CLIENTES"."GP_CURSOS_PK" 
   before insert on "GEST_CLIENTES"."GP_FORMACAO_TEST_CURSOS" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_CURSO" is null then 
         select GP_CURSOSEQ.nextval into :NEW."ID_CURSO" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "GEST_CLIENTES"."GP_CURSOS_PK" ENABLE;
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
